### ISSUE TITLE
_sendSMS does not send the sms/mms, only loads into the phone's message app.

### ISSUE THREAD

**Issue by pahoel** [fluttercommunity/flutter_sms#19]
This plugin is great!

I only have one questions:
The _sendSMS method does not actually send the message to the recipients. It only loads the message and recipients into the Android message app, ready for sending. The user has to manually send the message. 
Is this by design?
I need the message to be sent automatically, without any user intervention...

**Comment by gpibarra** [comment]
Just launch the native application to send messages.
If you really want to send an SMS you can try this package (Android only, not compatible with iOS due to permission limitations)
[https://github.com/geordyvcErasmus/flutter_sms](https://github.com/geordyvcErasmus/flutter_sms)
[https://pub.dev/packages/sms_maintained](https://pub.dev/packages/sms_maintained)

**Comment by pahoel** [comment]
Thanks!
I really like your plugin, especially since it handles multiple recipients (which is a problem with native Android SmsManager) and the automatic mms solution.
My SOS-app has a "dead man" function - which requires unattended sending of a rescue sms...

**Comment by rodydavis** [comment]
IOS and Android Soon will not allow sending automatically. Unless you are a phone or messaging app on android your app will be rejected
